export {default as LoginPage} from './LoginPage'
export {default as Historia2Page} from './Historia2Page'
export {default as Historia3Page} from './Historia3Page'
export {default as Historia5Page} from "./Historia5Page"
export {default as Historia10Page} from "./Historia10Page"
export {default as Historia14Page} from "./Historia14Page"
export {default as Historia7Page} from "./Historia7Page"
export {default as Historia8Page} from "./Historia8Page"
export {default as Historia15Page} from "./Historia15Page"
export {default as HistoriaExtraPage} from "./HistoriaExtraPage"
export {default as GamePage} from "./GamePage"